apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-ingress
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Values.firstServiceDomainPrefix }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.firstServiceName }}"
                port:
                  number: 80
          - path: /{{ .Values.secondServiceDomainPrefix }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.secondServiceName }}"
                port:
                  number: 80