apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.Environment }}-{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-box1"
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "50%"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.Environment }}-{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Values.Environment }}-{{ .Release.Name }}"
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: "{{ .Values.Environment }}-{{ .Release.Name }}"
      annotations:
        revision: {{ .Release.Revision | quote }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: "{{ .Release.Name }}-nginx"
          image: nginxdemos/hello
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "20Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "3"]