id = "${TEST_ENV}" # It could be your ${CI_SLUG} for example
name = "test environment"
namespace = "test"
variables = ".env"

[[boxes]]
type = "helm"
chart = "box1/Chart.yaml"
values = "box1/values.yaml"
name = "first-box-2"
    [[boxes.applications]]
    name = "service-nginx-1"
    chart = "box1/templates/api-nginx-service.yaml"
    [[boxes.applications]]
    name = "deployment-nginx-1"
    chart = "box1/templates/api-nginx-deployment.yaml"

[[boxes]]
type = "helm"
chart = "box2/Chart.yaml"
values = "box2/values.yaml"
name = "second-box-2"
    [[boxes.applications]]
    name = "service-nginx-2"
    chart = "box2/templates/api-nginx-service.yaml"
    [[boxes.applications]]
    name = "deployment-nginx-2"
    chart = "box2/templates/api-nginx-deployment.yaml"

[[boxes]]
type = "helm"
chart = "ingress/Chart.yaml"
name = "third-box"
values = "ingress/values.yaml"
    [[boxes.applications]]
    name = "www-ingress-toml"
    chart = "ingress/templates/ingress.yaml"
