name = "test environment"
namespace = ""
tag = "test-env-1"
type = "helm"

[[boxes]]
chart = "box1/Chart.yaml"
values = "box1/Values.yaml"
tag = "box1"
    [[boxes.applications]]
    name = "service-nginx-1"
    chart = "box1/templates/api-nginx-service.yaml"
    [[boxes.applications]]
    name = "deployment-nginx-1"
    chart = "box1/templates/api-nginx-deployment.yaml"

[[boxes]]
chart = "box2/Chart.yaml"
values = "box2/Values.yaml"
tag = "box2"
    [[boxes.applications]]
    name = "service-nginx-2"
    chart = "box2/templates/api-nginx-service.yaml"
    [[boxes.applications]]
    name = "deployment-nginx-2"
    chart = "box2/templates/api-nginx-deployment.yaml"

[[boxes]]
chart = "ingress/Chart.yaml"
values = "ingress/Values.yaml"
    [[boxes.applications]]
    name = "www-ingress-toml"
    chart = "ingress/templates/ingress.yaml"
