id = "${TEST_ENV}" # It can be your ${CI_SLUG} for example
name = "test environment"
namespace = "test"
variables = "${PWD}/examples/environments/.env"

load_boxes_from = "https://raw.githubusercontent.com/twelvee/k8sbox/load-boxes-via-http/examples/environments/example_boxes.toml"