id = "${TEST_ENV}" # It can be your ${CI_SLUG} for example
name = "test environment"
namespace = "test"
variables = "${PWD}/examples/environments/.env"

load_boxes_from = "http://localhost:3000/example_boxes.toml"