id = "${TEST_ENV}" # It can be your ${CI_SLUG} for example
name = "test environment"
namespace = "test"
variables = "${PWD}/examples/environments/.env"

load_boxes_from = "https://raw.githubusercontent.com/twelvee/boxie/load-boxes-via-http/examples/environments/example_boxes.toml"
[load_boxes_headers]
    [load_boxes_headers.0]
    name = "Content-Type"
    value = "application/toml"
    [load_boxes_headers.1]
    name = "Accept"
    value = "application/toml"

