apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
  labels:
    helm/chart: "{{ .Values.serviceName }}"
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ .Values.serviceName }}"
    app.kubernetes.io/instance: "{{ .Values.serviceName }}"